In [1]:
import numpy as np

In [2]:
def proxgrad (X,Y, eta, w, l, ls=True,tol = 0.001, maxiter =1000):
    n,d = X.shape
    
    for t in range(maxiter):
        if ls :
            
            while(func((w-eta*(gradient(w,X,Y))),X,Y) > (func(w,X,Y) - (eta*(np.linalg.norm(gradient(w,X,Y))) **2)/2) ):
                eta = eta/2
        w_prev = w        
        z = w - eta * (gradient(w,X,Y))
        w = prox(z,eta,d,l)
        if abs(np.linalg.norm(w - w_prev)/eta) < tol:
            break
    return w

In [3]:
def func(w,X,Y):
    n,d = X.shape
    f = 0.0
    for i in range(n):
        z = np.inner(X[i],w) - Y[i]
        if -1<=z<=1:
            f_i = 0.5*(z**2)
        else:
            f_i = abs(z) - 0.5
        f += f_i
    f = f/n
    return f

In [4]:
def gradient(w,X,Y):
    n,d = X.shape
    G = np.zeros(d)
    for i in range(n):
        z = np.inner(X[i],w) - Y[i]
        if abs(z) >= 1:
            g_i = np.sign(z) * X[i]
        else:
            g_i = z * X[i]
        G = G+g_i
    G = G/n
    return G

In [5]:
def datagen(w, n = 100, d = 10,sigma = 1):
    #I don't know how to set the default w value
    '''
    if set_w:
       
    '''
    mean = np.zeros(d)
    I = np.identity(d)
    X = np.random.multivariate_normal(mean, I, n)
    y = np.inner(w, X)+np.random.normal(0,sigma,n)
    
    return X,y

In [6]:
def prox_template(w,eta):
    return proximal_map

In [7]:
def prox(w,eta,d,l):
    # l for lambda
    #l1 norm
    z = np.zeros(d)
    for i in range(d):
        if w[i] <-eta*l:
            z[i] = w[i] + eta*l
        elif w[i] >eta*l:
            z[i] = w[i] - eta*l
        
    return z

In [8]:
w = np.zeros(10)
w[0] = 1.0
w[1] = -1.0
w
X,y = datagen(w)

In [9]:
w_0 = np.zeros(X.shape[1])
w_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
w = proxgrad (X,y, 1, w_0, 0.1,ls=False,tol = 0.001, maxiter =1000)

In [11]:
w

array([ 0.92579747, -0.89901532,  0.        ,  0.        , -0.05815147,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [12]:
g = gradient(w,X,y)
g

array([-0.10003161,  0.10020462, -0.07104325,  0.08667328,  0.0998186 ,
       -0.04989117,  0.07643465, -0.04966673,  0.07065711, -0.00607223])

In [13]:
f = func(w,X,y)
f

0.3979915242315388

In [14]:
w = proxgrad (X,y, 1, w_0, 1,ls=True,tol = 0.001, maxiter =1000)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
f = func(w,X,y)
f

1.060581593187662

In [16]:
w = proxgrad (X,y, 1, w_0, 10,ls=True,tol = 0.001, maxiter =1000)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
f = func(w,X,y)
f

1.060581593187662

In [18]:
#2.9
import math
def prox(w,eta,d,l):
    # l for lambda
    #l1 norm
    z = np.zeros(d)
    for i in range(d):
        if abs(w[i]) > math.sqrt(2*l*eta):
            z[i] = w[i]
    return z

In [19]:
def proxgrad (X,Y, eta, w, l, ls=True,tol = 0.001, maxiter =1000):
    n,d = X.shape
    f = []
    for t in range(maxiter):
        
        if ls :
            h = func(w,X,Y)
            while(h > (func(w,X,Y) - (eta*(np.linalg.norm(gradient(w,X,Y))) **2)/2) ):
                eta = eta/2
                h = func((w-eta*(gradient(w,X,Y))),X,Y)
        w_prev = w
        z = w - eta * (gradient(w,X,Y))
        w = prox(z,eta,d,l)
        
        if abs(np.linalg.norm(w - w_prev)/eta) < tol:
            break
        # reference: http://www.stat.cmu.edu/~ryantibs/convexopt/lectures/prox-grad.pdf
        l0 = 0
        for i in range(d):
            if w[i] != 0 :
                l0 +=1
        f.append(func(w,X,Y) + l*l0)
    return t,w,f

In [20]:
w_input = w_0
w_input[0] = 1
w_input[1] = 0.2

In [21]:
t,w,f = proxgrad (X,y, 1, w_input, 0.1, ls=True,tol = 0.001, maxiter =1000)

In [22]:
t

46

In [23]:
w

array([1.00883254, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [24]:
f

[0.8697677193081536,
 0.8697325606657424,
 0.8697190585402524,
 0.8697131128577171,
 0.8697103202716452,
 0.8697089665800787,
 0.8697083000923554,
 0.8697079694023937,
 0.8697078046914911,
 0.8697077224940136,
 0.8697076814347006,
 0.869707660914891,
 0.8697076506574479,
 0.8697076455293419,
 0.8697076429654419,
 0.8697076416835302,
 0.8697076410425844,
 0.8697076407221139,
 0.869707640561879,
 0.8697076404817623,
 0.8697076404417035,
 0.8697076404216737,
 0.869707640411659,
 0.8697076404066522,
 0.8697076404041486,
 0.8697076404028969,
 0.8697076404022707,
 0.8697076404019577,
 0.8697076404018016,
 0.8697076404017231,
 0.8697076404016836,
 0.8697076404016648,
 0.8697076404016546,
 0.8697076404016492,
 0.8697076404016468,
 0.8697076404016459,
 0.8697076404016459,
 0.8697076404016454,
 0.8697076404016448,
 0.8697076404016448,
 0.8697076404016449,
 0.8697076404016443,
 0.869707640401644,
 0.8697076404016439,
 0.869707640401644,
 0.8697076404016443]

In [25]:
t,w,f = proxgrad (X,y, 1, w_input, 1, ls=True,tol = 0.001, maxiter =1000)

In [26]:
t

46

In [27]:
w

array([1.00883254, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [28]:
f

[1.7697677193081536,
 1.7697325606657426,
 1.7697190585402525,
 1.7697131128577173,
 1.769710320271645,
 1.7697089665800787,
 1.7697083000923555,
 1.7697079694023938,
 1.7697078046914911,
 1.7697077224940136,
 1.7697076814347006,
 1.7697076609148912,
 1.7697076506574478,
 1.769707645529342,
 1.769707642965442,
 1.7697076416835302,
 1.7697076410425843,
 1.769707640722114,
 1.769707640561879,
 1.7697076404817622,
 1.7697076404417036,
 1.7697076404216738,
 1.7697076404116592,
 1.769707640406652,
 1.7697076404041487,
 1.7697076404028969,
 1.7697076404022707,
 1.7697076404019576,
 1.7697076404018017,
 1.7697076404017231,
 1.7697076404016836,
 1.769707640401665,
 1.7697076404016547,
 1.7697076404016492,
 1.7697076404016467,
 1.7697076404016459,
 1.7697076404016459,
 1.7697076404016454,
 1.769707640401645,
 1.769707640401645,
 1.769707640401645,
 1.7697076404016443,
 1.769707640401644,
 1.769707640401644,
 1.769707640401644,
 1.7697076404016443]

In [29]:
t,w,f = proxgrad (X,y, 1, w_input, 10, ls=True,tol = 0.001, maxiter =1000)

In [30]:
t

1

In [31]:
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
f

[1.060581593187662]

In [33]:
# This one will not converge